# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Users
User.create({username: 'TyGooch', password:'password', profile_picture_url: 'http://res.cloudinary.com/dtatkxxcm/image/upload/v1472680415/NotPink_ppycej.jpg'})
User.create({username: 'paulKim', password:'password', profile_picture_url: 'https://upload.wikimedia.org/wikipedia/commons/2/25/Paul_Hansen_Kim.jpg'})
User.create({username: '49erfan', password:'password', profile_picture_url: 'https://dealermesh.com/New%20folder/images/profile/2219225-austin-carr-profile.jpg'})
User.create({username: 'sofiaSong', password:'password', profile_picture_url: 'http://therealdeal.com/wp-content/uploads/2014/01/sofia-song.jpg'})
User.create({username: 'pGarcia', password:'password', profile_picture_url: 'https://media.licdn.com/mpr/mpr/shrinknp_200_200/AAEAAQAAAAAAAAfFAAAAJGYxZDhkZjQ3LTJiMTQtNGE0Zi05MTg2LTMzZDQ1NmJiZWQ0NA.jpg'})



#Artist, Album, Songs
Artist.create({name: 'Tycho', genre:'ambient', artist_picture_url: 'https://jukely.imgix.net/a393dda6c2f451731fb593ee154ae37db56d348dab7262ed6aabd08cf379?ixlib=rb-0.3.5&w=750&h=656&fit=crop&s=0714fea9fba115413bf64f8a7df09770', header_image_url: 'http://blog.iso50.com/wp-content/uploads/2012/12/Tycho-WC13-header.jpg'})
  Album.create({title: 'Awake', artist_id: 1, album_picture_url: 'https://upload.wikimedia.org/wikipedia/en/c/ca/Tycho_-_Awake.png'})
    Song.create({title:'Awake', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473112406/1-01_Awake_ndwfn6.mp3', length: '283', album_id: 1, artist_id: 1})
    Song.create({title:'Montana', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473110522/1-02_Montana_xq2uzg.mp3', length: '326', album_id: 1, artist_id: 1})
    Song.create({title:'L', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473110564/1-03_L_m4puxs.mp3', length: '277', album_id: 1, artist_id: 1})
    Song.create({title:'Dye', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473110514/1-04_Dye_edewkw.mp3', length: '317', album_id: 1, artist_id: 1})
    Song.create({title:'See', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473110694/1-05_See_p8k1br.mp3', length: '318', album_id: 1, artist_id: 1})
    Song.create({title:'Apogee', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473110300/1-06_Apogee_r0xt5j.mp3', length: '260', album_id: 1, artist_id: 1})
    Song.create({title:'Spectre', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473110319/1-07_Spectre_xpyn8e.mp3', length: '226', album_id: 1, artist_id: 1})
    Song.create({title:'Plains', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473110955/1-08_Plains_tgcmzb.mp3', length: '197', album_id: 1, artist_id: 1})
  Album.create({title: 'Dive', artist_id: 1, album_picture_url: 'https://upload.wikimedia.org/wikipedia/en/1/11/Dive_tycho_album.jpg'})
    Song.create({title:'A Walk', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473112146/01_A_Walk_ovabaw.mp3', length: '316', album_id: 2, artist_id: 1})
    Song.create({title:'Hours', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473438856/02_Hours_mgjdvn.mp3', length: '344', album_id: 2, artist_id: 1})
    Song.create({title:'Daydream', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473112261/03_Daydream_aeh14o.mp3', length: '334', album_id: 2, artist_id: 1})
    Song.create({title:'Dive', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473112471/04_Dive_t2ntd5.mp3', length: '499', album_id: 2, artist_id: 1})
    Song.create({title:'Coastal Brake', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473111426/05_Coastal_Brake_wogx5p.mp3', length: '334', album_id: 2, artist_id: 1})
    Song.create({title:'Ascension', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473112887/06_Ascension_mvl5q4.mp3', length: '264', album_id: 2, artist_id: 1})
    Song.create({title:'Melanine', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473111103/07_Melanine_w7pjly.mp3', length: '173', album_id: 2, artist_id: 1})
    Song.create({title:'Adrift', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473438893/08_Adrift_yw35hy.mp3', length: '362', album_id: 2, artist_id: 1})
    Song.create({title:'Epigram', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473111186/09_Epigram_m1xbzw.mp3', length: '148', album_id: 2, artist_id: 1})
    Song.create({title:'Elegy', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473112433/10_Elegy_zlpnc8.mp3', length: '263', album_id: 2, artist_id: 1})
  Album.create({title: 'The Science of Patterns', artist_id: 1, album_picture_url: 'http://sentiospace.com/wp-content/uploads/2016/02/the-science-of-patterns-tycho-400x400.jpg'})
    Song.create({title:'Dream As A Memory', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473438979/01_Dream_As_A_Memory_fnrosi.mp3', length: '229', album_id: 3, artist_id: 1})
    Song.create({title:'Human Condition', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473438991/02_Human_Condition_ruvgav.mp3', length: '305', album_id: 3, artist_id: 1})
    Song.create({title:'Red Bridge', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473438992/03_Red_Bridge_has9dn.mp3', length: '368', album_id: 3, artist_id: 1})
    Song.create({title:'Systems', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473438986/04_Systems_sogqz6.mp3', length: '375', album_id: 3, artist_id: 1})
    Song.create({title:'In The End (Bonus Track)', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473438975/In_The_End_Bonus_Track_dcz4lg.mp3', length: '271', album_id: 3, artist_id: 1})

Artist.create({name: 'Alan Walker', genre:'edm', artist_picture_url: 'http://d19y6wq6pk1k2b.cloudfront.net/~/media/images/artists/alan%20walker/alan-walker-1000x1000.png?mw=1500', header_image_url: 'http://i.amz.mshcdn.com/vuXkF1M-eAn1zkdn6w5fQa7NY_s=/950x534/https%3A%2F%2Fblueprint-api-production.s3.amazonaws.com%2Fuploads%2Fcard%2Fimage%2F25098%2Falan.walker.jpg'})
  Album.create({title: 'Faded - Single', artist_id: 2, album_picture_url: 'http://a2.mzstatic.com/us/r30/Music69/v4/e6/52/ca/e652caf9-5769-cc74-ec37-d80e3b960505/cover600x600.jpeg'})
    Song.create({title:'Faded', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473179941/Alan_Walker_-_Faded_fqmwpd.mp3', length: '312', album_id: 4, artist_id: 2})
  Album.create({title: 'Spectre - Single', artist_id: 2, album_picture_url: 'https://i1.sndcdn.com/artworks-000102464647-ege94p-t500x500.jpg'})
    Song.create({title:'Spectre', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473438298/spectreAlanWalker_gtypqp.mp3', length: '226', album_id: 5, artist_id: 2})

Artist.create({name: 'Steve Aoki', genre:'edm', artist_picture_url: 'http://cdn2.thelineofbestfit.com/images/remote/http_cdn2.thelineofbestfit.com/media/2013/08/steve-aoki.jpeg', header_image_url: 'http://files.clubplanet.com/SiteFiles%5CArticleImages%5C6400%5Caoki_header.jpg'})
  Album.create({title: '4OKI', artist_id: 3, album_picture_url: 'http://www.steveaoki.com/site/wp-content/uploads/2016/07/SteveAoki.4OKIEP_800px.jpg'})
    Song.create({title:'ILYSM', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473182926/01_ILYSM_op4zbj.mp3', length: '200', album_id: 6, artist_id: 3})
    Song.create({title:'Dope Girlz', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473182932/02_Dope_Girlz_lyzwie.mp3', length: '234', album_id: 6, artist_id: 3})
    Song.create({title:'Bring The Funk Back', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473182934/03_Bring_The_Funk_Back_wecf3g.mp3', length: '267', album_id: 6, artist_id: 3})
    Song.create({title:'Kids', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473183673/Steve_Aoki_MORTEN_-_Kids_Official_Music_Video_Chapter_4_of_4_vigtlm.mp3', length: '199', album_id: 6, artist_id: 3})

Artist.create({name: 'Kendrick Lamar', genre:'hip hop', artist_picture_url: 'http://emorywheel.com/wp-content/uploads/2016/03/1556365_10152290789958092_885501008_o.jpg', header_image_url: 'http://rappingmanual.com/wp-content/uploads/2014/08/kendrick-lamar-00.jpg'})
  Album.create({title: 'Good Kid M.A.A.D City', artist_id: 4, album_picture_url: 'https://upload.wikimedia.org/wikipedia/en/9/93/KendrickGKMC.jpg'})
    Song.create({title:"Sherane a.k.a Master Splinter's Daughter", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473184906/01_Sherane_A.K.A._Master_Splinters_Daughter_jguohl.mp3', length: '273', album_id: 7, artist_id: 4})
    Song.create({title:"Bitch, Don't Kill My Vibe", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473184789/02_Bitch_Dant_Kill_My_Vibe_mztoso.mp3', length: '310', album_id: 7, artist_id: 4})
    Song.create({title:'Backseat Freestyle', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473184739/03_Backstreet_Freestyle_qn4cn2.mp3', length: '212', album_id: 7, artist_id: 4})
    Song.create({title:'The Art of Peer Pressure', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473184772/04_The_Art_Of_Peer_Pressure_w89vzg.mp3', length: '324', album_id: 7, artist_id: 4})
    Song.create({title:'Money Trees', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473184801/05_Money_Trees_Feat._Jay_Rock_hc40k0.mp3', length: '386', album_id: 7, artist_id: 4})
    Song.create({title:'Poetic Justice', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473184852/06_Poetic_Justice_Feat._Drake_1_lssksv.mp3', length: '300', album_id: 7, artist_id: 4})
    Song.create({title:'good kid', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473184978/07_Good_Kid_eibow1.mp3', length: '214', album_id: 7, artist_id: 4})
    Song.create({title:'m.A.A.d city', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473184913/08_M.A.A.D_City_Feat._MC_Eiht_vlybty.mp3', length: '350', album_id: 7, artist_id: 4})
    Song.create({title:'Swimming Pools (Drank)', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473184890/09_Swimming_Pools_Drank_Extended_Version_ryvu18.mp3', length: '313', album_id: 7, artist_id: 4})
    Song.create({title:"Sing About Me, I'm Dying of Thirst", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473184923/10_Sing_About_Me_Im_Dying_Of_Thirst_jkgugx.mp3', length: '723', album_id: 7, artist_id: 4})
    Song.create({title:'Real', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473184967/11_Real_Feat._Anna_Wise_Of_Sonnymoon_czbovp.mp3', length: '443', album_id: 7, artist_id: 4})
    Song.create({title:'Compton', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473184945/12_Compton_Feat._Dr._Dre_iyax21.mp3', length: '248', album_id: 7, artist_id: 4})
    Song.create({title:'The Recipe', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473184783/2-13_The_Recipe_Feat._Dr_Dre_Bonus_Track_w31n18.mp3', length: '353', album_id: 7, artist_id: 4})
  Album.create({title: 'To Pimp A Butterfly', artist_id: 4, album_picture_url: 'http://media.cleveland.com/ent_impact_home/photo/pimp-a-butterfly-aa71fd87e2c23639.png'})
    Song.create({title:"Wesley's Theory", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473439627/01_Wesley_s_Theory_feat._George_Clinton_Thundercat_m3wrcf.mp3', length: '287', album_id: 8, artist_id: 4})
    Song.create({title:'For Free?', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473439575/02_For_Free__Interlude_mgqylu.mp3', length: '130', album_id: 8, artist_id: 4})
    Song.create({title:'King Kunta', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473439603/03_King_Kunta_k58cth.mp3', length: '234', album_id: 8, artist_id: 4})
    Song.create({title:'Institutionalized', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473439621/04_Institutionalized_feat._Bilal_Anna_Wise_Snoop_Dogg_im8b5d.mp3', length: '271', album_id: 8, artist_id: 4})
    Song.create({title:'The Walls', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473439658/05_These_Walls_feat._Bilal_Anna_Wise_Thundercat_ybb4um.mp3', length: '300', album_id: 8, artist_id: 4})
    Song.create({title:'u', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473439627/06_u_cfx4rd.mp3', length: '268', album_id: 8, artist_id: 4})
    Song.create({title:'Alright', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473439658/07_Alright_ohxe0k.mp3', length: '219', album_id: 8, artist_id: 4})
    Song.create({title:'For Sale? (Interlude)', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473439720/08_For_Sale_Interlude_dfnxih.mp3', length: '291', album_id: 8, artist_id: 4})
    Song.create({title:'Momma', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473439729/09_Momma_lsskcq.mp3', length: '283', album_id: 8, artist_id: 4})
    Song.create({title:'Hood Politics', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473439740/10_Hood_Politics_sjknzv.mp3', length: '292', album_id: 8, artist_id: 4})
    Song.create({title:'How Much a Dollar Cost', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473439732/11_How_Much_a_Dollar_Cost_feat._James_Fauntleroy_Ronald_Isley_vuucqq.mp3', length: '261', album_id: 8, artist_id: 4})
    Song.create({title:'Complexion', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473439756/12_Complexion_A_Zulu_Love_feat._Rapsody_xxiaas.mp3', length: '263', album_id: 8, artist_id: 4})
    Song.create({title:'The Blacker The Berry', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473439773/13_The_Blacker_the_Berry_knrbkb.mp3', length: '328', album_id: 8, artist_id: 4})
    Song.create({title:"You Ain't Gotta Lie (Momma Said)", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473439790/14_You_Ain_t_Gotta_Lie_Momma_Said_mbcdtu.mp3', length: '241', album_id: 8, artist_id: 4})
    Song.create({title:'i', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473439803/15_i_kkdvr6.mp3', length: '336', album_id: 8, artist_id: 4})
    Song.create({title:'Mortal Man', audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473439829/16_Mortal_Man_imxulk.mp3', length: '727', album_id: 8, artist_id: 4})


Artist.create({name: 'ODESZA', genre:'ambient', artist_picture_url: 'https://i1.sndcdn.com/avatars-000097056058-s07lh7-t500x500.jpg', header_image_url: 'https://va.sndcdn.com/bg/soundcloud:sounds:191621466/Haywyre_Odesza_PPP_-_Visual_sound_image.jpg'})
  Album.create({title: "Summer's Gone", artist_id: 5, album_picture_url: 'http://www.stereofox.com/wp-content/uploads/2013/01/Odesza-Summers-Gone-SF.jpg'})
    Song.create({title:"Intro", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473440228/01_Intro_cg1fh9.mp3', length: '34', album_id: 9, artist_id: 5})
    Song.create({title:"How Did I Get Here", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473440260/02_How_Did_I_Get_Here_t1c1g8.mp3', length: '131', album_id: 9, artist_id: 5})
    Song.create({title:"I Want You", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473440276/03_I_Want_You_ahvgr8.mp3', length: '161', album_id: 9, artist_id: 5})
    Song.create({title:"Above the Middle", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473440253/04_Above_The_Middle_kkjxi8.mp3', length: '183', album_id: 9, artist_id: 5})
    Song.create({title:"We Were Young", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473440244/05_We_Were_Young_bzzxkw.mp3', length: '192', album_id: 9, artist_id: 5})
    Song.create({title:"Today", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473440289/06_Today_cvy6uq.mp3', length: '255', album_id: 9, artist_id: 5})
    Song.create({title:"Tuytus", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473440274/07_Tuytus_xz7a0s.mp3', length: '196', album_id: 9, artist_id: 5})
    Song.create({title:"Rely", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473440313/08_Rely_ysyzoz.mp3', length: '192', album_id: 9, artist_id: 5})
    Song.create({title:"Hey Now", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473440307/09_Hey_Now_hih7no.mp3', length: '148', album_id: 9, artist_id: 5})
    Song.create({title:"If You Don't (feat. Cumulus)", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473440331/10_If_You_Don_t_ft_Cumulus_fdxrwh.mp3', length: '187', album_id: 9, artist_id: 5})
    Song.create({title:"Don't Stop", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473440321/11_Don_t_Stop_fp1abg.mp3', length: '268', album_id: 9, artist_id: 5})
    Song.create({title:"IPlayYouListen", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473440343/12_IPlayYouListen_f9n07y.mp3', length: '292', album_id: 9, artist_id: 5})
  Album.create({title: "In Return", artist_id: 5, album_picture_url: 'https://i.ytimg.com/vi/oL4KJmMGda8/maxresdefault.jpg'})
    Song.create({title:"Always This Late", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473440939/01_Always_This_Late_jbh7yv.mp3', length: '180', album_id: 10, artist_id: 5})
    Song.create({title:"Say My Name (feat. Zyra)", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473440997/02_Say_My_Name_feat._Zyra_prbrou.mp3', length: '262', album_id: 10, artist_id: 5})
    Song.create({title:"Bloom", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473440937/03_Bloom_ek7yvp.mp3', length: '195', album_id: 10, artist_id: 5})
    Song.create({title:"All We Need (feat. Shy Girls)", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473440991/04_All_We_Need_feat._Shy_Girls_ahf3g5.mp3', length: '211', album_id: 10, artist_id: 5})
    Song.create({title:"Sundara", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473440956/05_Sundara_nbxozf.mp3', length: '136', album_id: 10, artist_id: 5})
    Song.create({title:"White Lies (feat. Jenni Potts)", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473441002/06_White_Lies_feat._Jenni_Potts_jollfu.mp3', length: '277', album_id: 10, artist_id: 5})
    Song.create({title:"Kusanagi", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473441019/07_Kusanagi_dzp0hm.mp3', length: '208', album_id: 10, artist_id: 5})
    Song.create({title:"Echoes (feat. Py)", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473441037/08_Echoes_feat._Py_o8rknm.mp3', length: '264', album_id: 10, artist_id: 5})
    Song.create({title:"It's Only (feat. Zyra)", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473441061/09_It_s_Only_feat._Zyra_h3l1yl.mp3', length: '268', album_id: 10, artist_id: 5})
    Song.create({title:"Koto", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473441067/10_Koto_focpos.mp3', length: '194', album_id: 10, artist_id: 5})
    Song.create({title:"Memories That You Call", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473441079/11_Memories_That_You_Call_feat._Monsoonsiren_uau7iq.mp3', length: '248', album_id: 10, artist_id: 5})
    Song.create({title:"Sun Models", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473441065/12_Sun_Models_feat._Madelyn_Grant_zxicnk.mp3', length: '160', album_id: 10, artist_id: 5})
    Song.create({title:"For Us", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473441101/13_For_Us_feat._Briana_Marela_muptg0.mp3', length: '349', album_id: 10, artist_id: 5})

Artist.create({name: 'Ariana Grande', genre:'pop', artist_picture_url: 'http://www.rap-up.com/wp-content/uploads/2014/12/ariana-grande.jpg', header_image_url: 'http://i.imgur.com/TncvYJo.png'})
  Album.create({title: "Dangerous Woman", artist_id: 6, album_picture_url: 'https://upload.wikimedia.org/wikipedia/en/4/4b/Ariana_Grande_-_Dangerous_Woman_%28Official_Album_Cover%29.png'})
    Song.create({title:"Moonlight", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473447896/01_-_Moonlight_lodlfh.mp3', length: '202', album_id: 11, artist_id: 6})
    Song.create({title:"Dangerous Woman", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473447956/02_-_Dangerous_Woman_jttlpa.mp3', length: '236', album_id: 11, artist_id: 6})
    Song.create({title:"Be Alright", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473447853/03_-_Be_Alright_aqpb1h.mp3', length: '177', album_id: 11, artist_id: 6})
    Song.create({title:"Into You", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473447979/04_-_Into_You_ges447.mp3', length: '244', album_id: 11, artist_id: 6})
    Song.create({title:"Side to Side", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473447939/05_-_Side_To_Side_feat._Nicki_Minaj_ekywwp.mp3', length: '226', album_id: 11, artist_id: 6})
    Song.create({title:"Let Me Love You", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473447943/06_-_Let_Me_Love_You_feat._Lil_Wayne_exrjc1.mp3', length: '223', album_id: 11, artist_id: 6})
    Song.create({title:"Greedy", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473448220/07_-_Greedy_gpfjg1.mp3', length: '214', album_id: 11, artist_id: 6})
    Song.create({title:"Leave Me Lonely", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473448264/08_-_Leave_Me_Lonely_feat._Macy_Gray_huxswk.mp3', length: '229', album_id: 11, artist_id: 6})
    Song.create({title:"Everyday", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473448248/09_-_Everyday_feat._Future_a6nqjz.mp3', length: '214', album_id: 11, artist_id: 6})
    Song.create({title:"Bad Decisions", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473448343/12_-_Bad_Decisions_j1hr5p.mp3', length: '226', album_id: 11, artist_id: 6})
    Song.create({title:"Thinking Bout You", audio_url: 'http://res.cloudinary.com/dtatkxxcm/video/upload/v1473448262/15_-_Thinking_Bout_You_e3dlny.mp3', length: '200', album_id: 11, artist_id: 6})

#Playlists
Playlist.create({name: 'Summer 2016', user_id: '1'})
  PlaylistSong.create({playlist_id: 1, song_id: 1})
  PlaylistSong.create({playlist_id: 1, song_id: 3})
  PlaylistSong.create({playlist_id: 1, song_id: 15})
  PlaylistSong.create({playlist_id: 1, song_id: 9})
  PlaylistSong.create({playlist_id: 1, song_id: 3})
